# Custom nav
nav:
  title: "ciyuandao"

favicon: ""

# Custom background
background:
  color: "#eff0f6"
  image: ""

# Social media
social:
  官方微博: /
  官方微信: /
  抖音: /
  # GitHub: https://github.com/cloverTuan

# Custom footer
mail: ciyuandao@163.com
copyright: All rights reserved @ciyuandao

# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  # Project: /
  首页: /
  #Archive: /categories
  资讯: /categories
  联系我们: /about

# Specific default categories or tags of home page.
# Post which belongs to `category` or `tag` and don't belongs to `except_category` or `except_tag` will be filtered.
home:
  # set card style of home page
  tag: Blog
  # category: Project
  # tag: 算法
  # except_category: 树
  # except_tag:
  #   - 总结
  #   - css

card_style:
  home: project-card
  archive: article-card
  tag: project-card
  category: article-card

# category page
category_generator:
  category_per_page: 3
  post_per_category: 3

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false